[package]
name = "hypua_node_native"
version = "0.1.0"
edition = "2021"
authors = ["pikokr <parangee9706@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
hypua = "0.2.0"
wasm-bindgen = "0.2"
